### ISSUE TITLE
Plugin incopatible with  IDEA 2018.2.5

### ISSUE THREAD

**Issue by SzymonWiedeheft** [JavaSaBr/IntelliJ-jME-Plugin#5]
Hi, 
When i am trying to install latest plugin from disk I get 'Plugin 'jMonkeyEngine Support' is incompatible with this installation' also when browsing plugins repository in idea i cannot find it.

IDEA info:
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
Linux 4.15.0-38-generic

**Comment by JavaSaBr** [comment]
hm, I will check it

**Comment by TalosDx** [comment]
Поддерживаю, ошибка:
`> taskdef A class needed by class com.intellij.ant.InstrumentIdeaExtensions cannot be found: org/jetbrains/org/objectweb/asm/ClassWriter
   using the classloader AntClassLoader[C:\Users\talos\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2018.3\6edb21dc38f8114a1ac506d6bea87fcf85955a6\ideaIC-2018.3\lib\javac2.jar;C:\Users\talos\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2018.3\6edb21dc38f8114a1ac506d6bea87fcf85955a6\ideaIC-2018.3\lib\jdom.jar]` при сборе с помощью gradle;

**Comment by TalosDx** [comment]
Пардон, сначала поменял просто до 2018.3
`intellij {
    version '2018.3'
    plugins = ['coverage', 'gradle']
    pluginName 'IntelliJ-jME-Plugin'
}`
Но потом увидел строку:
`id "org.jetbrains.intellij" `
И обновил с 0.3.1 до 0.3.12 плагин успешно собрался.
Всё ок плагин встал.

**Comment by TalosDx** [comment]
=_= пофиксил блин во вкладке gradle'а нет создания jme проекта, и вкладка jMonkeyEngine просто не открывается.

**Comment by lightway82** [comment]
В репозитории https://plugins.jetbrains.com/plugin/10333-jmonkeyengine-support лежит старая версия

**Comment by bvn13** [comment]
@SzymonWiedeheft @lightway82 I have created pull request for this update https://github.com/JavaSaBr/IntelliJ-jME-Plugin/pull/7
@JavaSaBr accept it please

**Comment by JavaSaBr** [comment]
@bvn13 done, thanks
